### ISSUE TITLE
Second (and beyond) `git push` to builder fails

### ISSUE THREAD

**Issue by arschles** [deis/builder#41]
... because the `deis-slugbuilder` pod already exists. The below output is from builder after a `git push` has completed:

```console
core@micro-kube ~/example-go $ echo "Asd" >> README.md && git commit -a -m "AsdA" && git push deis master
[master 9b67c28] AsdA
 1 file changed, 1 insertion(+)
Counting objects: 177, done.
Compressing objects: 100% (163/163), done.
Writing objects: 100% (177/177), 3.02 MiB | 6.00 KiB/s, done.
Total 177 (delta 89), reused 0 (delta 0)
Added host ‘http://10.3.0.93:9000’ successfully.
mc: <ERROR> Unable to make bucket ‘http://10.3.0.93:9000/git’. The requested bucket name is not available.
‘rococo-seashore.tar.gz’ -> ‘http://10.3.0.93:9000/git/home/rococo-seashore:git-9b67c28e/tar’
Total: 2.97 MB, Transferred: 2.97 MB, Speed: 51.66 MB/s
stored tarfile in http://10.3.0.93:9000/git/home/rococo-seashore:git-9b67c28e/tar
creating slugbuilder in namespace deis
Error from server: error when creating "/etc/rococo-seashore:git-9b67c28e.yaml": pods "deis-slugbuilder" already exists
To ssh://git@10.3.0.215:2222/rococo-seashore.git
 * [new branch]      master -> master
```

Note that the first `deis-slugbuilder` that launched as a result of the push did not succeed, so fixing that issue may fix this one for the `v2.0-alpha1` release. In the future, Builder should be more robust to `deis-slugbuilder` failures. See https://github.com/deis/slugbuilder/issues/10 for more details.

**Comment by bacongobbler** [comment]
perhaps a UUID for the build would be useful here?

**Comment by arschles** [comment]
+1

**Comment by smothiki** [comment]
It should not be saying ```Error from server: error when creating "/etc/rococo-seashore:git-9b67c28e.yaml": pods "deis-slugbuilder" already exists```  because we are changing POD names to <appname>:git-<sha:8>. How's metadata of  POD template for rococo-seashore:git-9b67c28e.yaml look like

**Comment by arschles** [comment]
@smothiki see below:

```yaml
ENG000656:slugbuilder aaronschlesinger$ kd exec deis-builder-k06of -- cat /etc/rococo-seashore:git-9b67c28e.yaml
apiVersion: v1
kind: Pod
metadata:
  name: deis-slugbuilder
  labels:
    heritage: deis
    version: v2-alpha
spec:
  restartPolicy: Never
  containers:
    - name: deis-slugbuilder
      imagePullPolicy: Always
      image: quay.io/deisci/slugbuilder:v2-alpha
      env:
        - name: DEBUG
          value: "1"
        - name: TAR_URL
          value: http://10.3.0.93:9000/git/home/rococo-seashore:git-9b67c28e/tar
        - name : put_url
          value: http://10.3.0.93:9000/git/home/rococo-seashore:git-9b67c28e/push
      volumeMounts:
        - name: minio-user
          mountPath: /var/run/secrets/object/store
          readOnly: true
  volumes:
    - name: minio-user
      secret:
        secretName: minio-user
```

were we using `repo_name` to set the pod name (https://github.com/deis/builder/blob/master/rootfs/etc/confd/templates/builder#L115)? I believe I removed that from the slugbuilder template inside builder. If so, :facepalm: and I'll move it back.
