### ISSUE TITLE
Deploys fail with PORT needs to be set in the config when using a private registry

### ISSUE THREAD

**Issue by foxycoder** [deis/builder#433]
I have set up workflow to use `gcr` on `eu.gcr.io`. On workflow v2.3.0 this worked just fine with the setup below, I think, but I might have missed something.

When I deploy, I get:

```
Pushing to registry
Build complete.
Launching App...
remote: 2016/09/26 21:50:53 Error running git receive hook [publishing release (Unknown Error (400): {"detail":"PORT needs to be set in the config when using a private registry"})]
```

Below part of my `generate_params.toml` (key_json cleaned):

```toml
# Set the location of Workflow's Registry
#
# Valid values are:
# - on-cluster: Run registry within the Kubernetes cluster
# - off-cluster: Use registry outside the Kubernetes cluster (example: dockerhub,quay.io,self-hosted)
# - ecr: Use Amazon's ECR
# - gcr: Use Google's GCR
registry_location = "gcr"

# ...

[gcr]
key_json = '''{"actual":"key","present":"here"}'''
hostname = "eu.gcr.io"
```

In `deis-registry-token-refresher.yaml` I have:

```yaml
            - name: "DEIS_REGISTRY_SECRET_PREFIX"
              value: "private-registry"
```

### Version Info

- Workflow 2.5.0
- GKE Master/Node version 1.3.7
