### ISSUE TITLE
Builder error on second push

### ISSUE THREAD

**Issue by slack** [deis/builder#49]
Pushing an app a second time ran into at least two issues:
1. git bucketname already exists
2. pod name `deis-dockerbuilder` already existed

```console
example-dockerfile-http [master]$ g push deis master
Counting objects: 47, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (37/37), done.
Writing objects: 100% (47/47), 7.16 KiB | 0 bytes/s, done.
Total 47 (delta 6), reused 0 (delta 0)
Added host ‘http://10.3.0.133:9000’ successfully.
mc: <ERROR> Unable to make bucket ‘http://10.3.0.133:9000/git’. The requested bucket name is not available.
‘shadow-woodshed.tar.gz’ -> ‘http://10.3.0.133:9000/git/home/shadow-woodshed:git-3edec618/tar’
Total: 2.00 KB, Transferred: 2.00 KB, Speed: 801.59 KB/s
-----> stored tarfile in http://10.3.0.133:9000/git/home/shadow-woodshed:git-3edec618/tar
-----> creating builder pod in namespace deis
Error from server: error when creating "/etc/shadow-woodshed:git-3edec618.yaml": pods "deis-dockerbuilder" already exists
To ssh://git@a097f2098a2ce11e5a5a40272b026e4b-190952671.us-west-2.elb.amazonaws.com:2222/shadow-woodshed.git
 * [new branch]      master -> master
```

Also issues with deisci/dockerbuilder image
```
Failed to pull image "quay.io/deisci/dockerbuilder:v2-alpha": image pull failed for quay.io/deisci/dockerbuilder:v2-alpha, this may be because there are no credentials on this request.  details: (Error: Status 403 trying to pull repository deisci/dockerbuilder: "{\"error\": \"Permission Denied\"}")
```

**Comment by slack** [comment]
```
-rw-r--r-- 1 root root 1017 Dec 15 22:12 /etc/shadow-woodshed:git-3edec618.yaml
/ # cat /etc/shadow-woodshed:git-3edec618.yaml
apiVersion: v1
kind: Pod
metadata:
  name: deis-dockerbuilder
  labels:
    heritage: deis
    version: v2-alpha
spec:
  restartPolicy: Never
  containers:
    - name: deis-dockerbuilder
      imagePullPolicy: Always
      image: quay.io/deisci/dockerbuilder:v2-alpha
      env:
        - name: DEBUG
          value: "1"
        - name: TAR_URL
          value: http://10.3.0.133:9000/git/home/shadow-woodshed:git-3edec618/tar
        - name: IMG_NAME
          value: imagename
        - name: ACCESS_KEY_FILE
          value: /var/run/secrets/object/store/access_key
        - name: ACCESS_SECRET_FILE
          value: /var/run/secrets/object/store/access_secret
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
        - name: minio-user
          mountPath: /var/run/secrets/object/store
          readOnly: true
  volumes:
    - name: minio-user
      secret:
        secretName: minio-user
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
/ #
```
